services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - mongo-data:/data/db

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: db_init
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "6500:6500"
    depends_on:
      - mysql
      - mongodb
    env_file:
      - .env
    command: python test_db.py

volumes:
  mongo-data:
  mysql-data:
